now supports hashes

diff --git a/regress b/regress
--- a/regress
+++ b/regress
@@ -1,8 +1,13 @@
 #!/bin/bash
-# $Id: regress,v 1.3 2003/09/23 19:20:28 doug Exp $
+# $Id: regress,v 1.4 2004/03/27 13:05:10 doug Exp $
 # regression test sets for EXACT
 # note: this script isn't portable, and may blow up on you.
 #       it's really designed for my own regression tests.
+
+regdir=`pwd`/t
+
+DEBUG=""
+[ "$1" == "-d" ] && DEBUG=1
 
 mkconfig () {
     
@@ -14,6 +19,8 @@ mkconfig () {
         -e "s,@ac_cv_user\@,$username,g"            \
         -e "s,@ac_cv_group\@,$groupname,g"          \
         -e "s,@ac_cv_watch\@,$watchfile,g"          \
+        -e "s,@ac_cv_authtype\@,$authtype,g"        \
+        -e "s,@ac_cv_server\@,uw-imap,g"            \
         -e "s,@logging@,internal,g"                 \
         -e 's,@timeout\@,180,g'                     \
         -e 's,@flush\@,30,g'                        \
@@ -24,7 +31,6 @@ mkconfig () {
 
 cleanroom () {
     # remove and create the regression test directory
-    regdir=`pwd`/t
     rm -rf "$regdir"
     [ -d "$regdir" ] || {
         mkdir "$regdir"
@@ -39,6 +45,7 @@ cleanroom () {
     export username=`id -un`
     export groupname=`id -gn`
     export watchfile=$regdir/watch
+    [ -z "$authtype" ] && export authtype=text
     mkconfig exact.conf.in
     cp exact-servers.conf $regdir
 }
@@ -56,6 +63,22 @@ killexact () {
     kill `cat $regdir/run/exact/exact.pid` && sleep 1
 }
 
+runexact () {
+    touch $watchfile
+    if [ "$DEBUG" ]; then
+        echo run -fdc $regdir/reg.conf > gdb-commands
+        gdb ./exact -x gdb-commands &
+    else
+        ./exact -fdc $regdir/reg.conf &
+    fi
+    sleep 2
+    pid=`cat $regdir/run/exact/exact.pid`
+    kill -s 0 $pid || {
+        echo "Error: exact not started"
+        exit 1
+    }
+}
+
 ### Test 1
 #
 # Very basic.
@@ -63,9 +86,7 @@ killexact () {
 test1 () {
     echo Starting Test 1
     cleanroom
-    touch $watchfile
-    ./exact -c $regdir/reg.conf
-    sleep 2
+    runexact
     cat "td1-1" > $watchfile
     sleep 10
     killexact
@@ -79,9 +100,7 @@ test1a () {
     echo Starting Test 1a
     cleanroom
     mkconfig exact.conf.in.cyrus
-    touch $watchfile
-    ./exact -c $regdir/reg.conf
-    sleep 2
+    runexact
     cat "td1-2" > $watchfile
     sleep 10
     killexact
@@ -96,9 +115,7 @@ test1a () {
 test2 () {
     echo Starting Test 2
     cleanroom
-    touch $watchfile
-    ./exact -c $regdir/reg.conf
-    sleep 2
+    runexact
     cat "td2-1" > $watchfile
     sleep 10
     cat "td2-2" >> $watchfile
@@ -111,7 +128,6 @@ test2 () {
 test3 () {
     echo Starting Test 3
     cleanroom
-    touch $watchfile
     ./exact -pc $regdir/reg.conf
     sleep 2
     cat "td2-1" > $watchfile
@@ -133,6 +149,24 @@ test4 () {
     sleep 2
 }
 
+### Test 5 
+#
+# berkeley db
+
+test5 () {
+    echo Starting Test 5
+    authtype=db
+    cleanroom
+    runexact
+    cat "td1-1" > $watchfile
+    sleep 5
+    killexact
+    diff t/log/exact/exact.log tr1
+    report 5
+}
+
+test5
+exit
 test4
 test1
 test1a
